Sugiro adicionar "verify=False" (veja abaixo).
De alguma forma, quando instalado no google colab, o sidra rejeita o request por falha na conexão SSL (veja um exemplo):
SSLError: HTTPSConnectionPool(host='apisidra.ibge.gov.br', port=443): Max retries exceeded with url: /values/t/1613/n6/3149804/p/1974-2020/v/2313,216,214,112 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))